---
    - name: install nfs-utils
      yum: name=nfs-utils

    - name: restart nfs-server
      service: name=nfs-server state=restarted

    - name: restart rpcbind
      service: name=rpcbind state=restarted

    
